### PR TITLE
Switch to using GoLevelDB

### LINKED ISSUE #33: Explore faster database options
BoltDB is quite simply brilliant, but its write-speeds are not adequate.

Some alternatives include:

* https://github.com/syndtr/goleveldb/
* https://github.com/siddontang/ledisdb
* https://github.com/HouzuoGuo/tiedot
* https://github.com/peterbourgon/diskv

Speed is the primary concern. Usability is important too, and it should be pure-go. I'm leaning towards LevelDB at the moment.

### PR DESCRIPTION
**Pull request by awnumar**
Implemented using https://github.com/syndtr/goleveldb/

Credits to @dotcppfile 

Closes #33

### CODE REVIEW

**Comment by takhlaq** [comment]
why not submodule?

**Comment by awnumar** [comment]
What do you mean?

**Comment by takhlaq** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Submodules
instead of manually committing their files (mainly cause i dont like the massive number of files changed)

**Comment by awnumar** [comment]
We're using [glide.sh](https://glide.sh). It's a package management system for Golang, and it gives us high reliability and reproducibility. It uses vendoring (a standard Golang feature) to accomplish this, which is why we're committing a large number of files.

The good news is we only commit them once, and then everyone who builds the project uses the local version of the dependency.

**Comment by tobbbles** [comment]
@libeclipse Also removes possibility of a leftpad.

**Comment by awnumar** [comment]
@mnzt yep, that too

**Pull request merged**
